refactor cookies
DTStack/dt-react-component pull request #294
Opened 2023-04-04 09:09 UTC by JackWang032

### 重构Cookies组件

变更点

- React Hook重构
- 单测补全
- 增加属性 intervalTime 控制轮询比较间隔
- 逻辑变动，cookie初始值变更，原先为空字符串，会导致每次组件挂载时比较都会触发一次onChanged，现改为document.cookie

2023-04-06 07:16 UTC, mumiao commented
这个组件Review 需要 @liuxy0551 @Zaoei   负责跟进

2023-04-13 03:16 UTC, mortalYoung commented
我感觉这个 Cookie 更像一个 hooks 0.0 是不是应该改造成类似于 useEffect 的自定义 hooks 比较好

2023-04-13 03:17 UTC, Zaoei requested changes

2023-04-14 01:20 UTC, liuxy0551 commented on src/cookies/index.tsx
> +    const onFieldsChange = (oldCookies: string, newCookies: string) => {
内部的方法名建议不和 props 的 `onFieldsChanged` 太接近，没那么易读，可以考虑以 `handle` 开头命名为 `handleFieldsChange`

2023-04-17 09:32 UTC, JackWang032 commented
已改成hook形式， @mortalYoung ， 看下使用方式是否合理，单测暂未修复

2023-04-17 10:05 UTC, mortalYoung requested changes

2023-04-17 10:05 UTC, mortalYoung commented on src/cookies/index.tsx
> +    oldCookies: string;
要不叫 prevCookies 和 nextCookies 我看类似的 `componentDidUpdate` 里面的参数名字叫 prevProps，我们类比一下好了

2023-04-17 10:05 UTC, mortalYoung commented on src/cookies/index.tsx
> +const useCookieListener = (
要不叫 `useCookieEffect`，参考一下 useEffect 的参数命名
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/18719701/232453424-68497081-2a4e-4036-8872-801d5e3f6840.png">

2023-04-17 11:16 UTC, JackWang032 commented on src/cookies/index.tsx
> +const useCookieListener = (
我觉得更倾向于ahooks的useEventListener

2023-04-17 11:17 UTC, mortalYoung commented on src/cookies/index.tsx
> +const useCookieListener = (
也阔以 没啥问题

2023-04-18 10:09 UTC, mumiao commented on src/cookies/index.tsx
> +    const onFieldsChange = (oldCookies: string, newCookies: string) => {
内部方法名用`handle`, 外部传入的用`on`监听

2023-04-18 10:09 UTC, mumiao commented on src/cookies/index.tsx
> +    intervalTime?: number; // 轮训间隔
+1

2023-04-20 02:47 UTC, mumiao commented
changelog更新下

2023-04-20 07:15 UTC, merged