WIP refactor: fullscreen component refactor
DTStack/dt-react-component pull request #304
Opened 2023-04-13 12:15 UTC by shiqiWang0

## 重构 Fullscreen 组件
### 组件背景
用来实现全屏切换的组件
### 变更点
1. React Hook重构；
2. 代码按着函数的单一职责重新封装函数；
3. 默认样式替换；
4. 单测补充；
5. doc 示例补充；
### 预览地址
https://shiqiwang0.github.io/dt-react-component/components/fullscreen

2023-04-14 02:49 UTC, mortalYoung requested changes

2023-04-14 02:49 UTC, mortalYoung commented on src/fullscreen/index.tsx
> +    const fullScreen = (): void => {
这几个函数的名字都优化一下吧，遵循内部函数用 handle 开头，外部函数用 on 开头吧 0.0

2023-04-14 02:49 UTC, mortalYoung commented on src/fullscreen/icon.tsx
这个组件也顺手改成 function 的吧

2023-04-14 02:49 UTC, mortalYoung commented on src/fullscreen/index.tsx
>  export interface FullscreenProps {
```suggestion
export interface IFullscreenProps {
```

2023-04-14 02:49 UTC, mortalYoung commented on src/fullscreen/index.tsx
>  export interface FullscreenProps {
这个类型里面不要去定义 `[propName: string]: any` 这种，我建议显式的声明该组件需要的 props 类型，或者 extend `HTMLSpanElement`

2023-04-14 08:49 UTC, mumiao commented on src/fullscreen/demos/custom.tsx
> +                <>
![image](https://user-images.githubusercontent.com/22880945/231994057-d1cf39de-ca7d-4e02-8b22-5cca5e7c63a1.png)
触发器上加个小手的状态，表示可点击的状态

2023-04-16 06:28 UTC, mortalYoung requested changes

2023-04-16 06:28 UTC, mortalYoung commented on src/fullscreen/index.tsx
>      iconStyle?: object;
这个类型改一下，`React.CSSProperties`

2023-04-16 06:28 UTC, mortalYoung commented on src/fullscreen/index.tsx
> +            domEle.addEventListener('fullscreenchange', () => callBack?.());
这里想个办法，addEventListener 之后 remove 掉，按照现有的逻辑应该是没有 remove 掉的

2023-04-19 08:31 UTC, mortalYoung approved these changes
+1

2023-04-20 11:25 UTC, mumiao commented
changelog更新下 https://dtstack.yuque.com/rd-center/tqk74v/mpvba83z25nrzws2#pCo3a @shiqiWang0

2023-04-20 11:25 UTC, mumiao approved these changes

2023-04-20 11:25 UTC, merged