Refactor/modalWithForm
DTStack/dt-react-component pull request #305
Opened 2023-04-13 12:27 UTC by Zaoei

重构代码
1、分别继承 modal 和 from 的 props， 使用 useFilterProps 进行区分
2、在 `afterClose` 中重置 form 表单
3、增加 [react-test-renderer](https://github.com/DTStack/dt-react-component/commit/ce3372bdffedfa38ec27b46b2f278372345fe439) 依赖，解决 renderHooks 报错
4.  完善文档

预览地址
https://zaoei.github.io/dt-react-component/components/modal-with-form

2023-04-14 02:57 UTC, mortalYoung requested changes

2023-04-14 02:57 UTC, mortalYoung commented on src/modalWithForm/demos/basics.tsx
> +            <Modal
可以考虑这么写吗，个人感觉现在很少有用到 HOC 的写法了
```jsx
<ModalWithForm {...props}>
 {(_props) => (
    <Form.Item label="username" name={'username'} rules={[{ max: 10 }]}>
         <Input />
     </Form.Item>
  )}
</ModalWithForm>
```

2023-04-14 02:57 UTC, mortalYoung commented on src/modalWithForm/index.tsx
> +    hideModalHandler?: () => void;
如果这个参数准备弃用了，可以加一个 `@deprecated`

2023-04-14 02:57 UTC, mortalYoung commented on src/modalWithForm/index.tsx
> +export const useFilterProps = (props: { [key: string]: any }, basis: string[]) => {
这个是不是可以抽一个 hook 组件出来

2023-04-14 02:57 UTC, mortalYoung commented on src/modalWithForm/index.tsx
> +        props.onCancel?.();
这里应该是 `(props.onCancel || hideModelhandler)()` 来防止执行两次吧 0.0

2023-04-14 05:55 UTC, mumiao commented on src/modalWithForm/index.tsx
>  export default ModalWithForm;
命名跟https://github.com/DTStack/dt-react-component/pull/296这个规范一致，改成: Modal.form,  cc @mortalYoung

2023-04-14 05:55 UTC, mumiao commented on src/modalWithForm/demos/basics.tsx
> +            <Modal
这是render props的写法，可以的

2023-04-14 07:26 UTC, Zaoei commented on src/modalWithForm/index.tsx
> +        props.onCancel?.();
好，虽然这种情况出现的可能性比较小

2023-04-14 08:26 UTC, mumiao commented on src/modalWithForm/index.tsx
> +        props.onCancel?.();
这个直接deprecated把，迁移的时候直接让开发改一下，要不然就成历史包袱了

2023-04-17 12:19 UTC, mortalYoung requested changes

2023-04-17 12:19 UTC, mortalYoung commented on src/utils/index.ts
> +    filterPropsByAntdProps(props: { [key: string]: any }, antdPropsList: string[][]) {
感觉可以更抽象一点，其实和 antd 不耦合的。主要功能就是把一个 object 做分类，考虑 filter 或者 group

2023-04-17 12:21 UTC, mumiao commented on src/utils/index.ts
> +    filterPropsByAntdProps(props: { [key: string]: any }, antdPropsList: string[][]) {
这个名字还带了antd这个名字，其实就是个属性筛选

2023-04-18 09:58 UTC, mumiao approved these changes

2023-04-18 09:58 UTC, mumiao commented on src/modal/demos/basics.tsx
> +import { Modal } from 'dt-react-component';
导入路径有问题，Modal.form

2023-04-18 09:58 UTC, mumiao commented on src/modal/demos/advance.tsx
> +import { ModalWithForm } from 'dt-react-component';
导入路径有问题

2023-04-18 09:58 UTC, mumiao commented on src/modal/index.md
> +title: ModalWithForm 带表单的模态框
Modal.form

2023-04-20 04:21 UTC, mumiao commented on src/modal/modalWithForm.tsx
> +export interface ModalProps<Values = any, Record = any> extends FormProps, ModalFuncProps {
```suggestion
export interface IModalFormProps<Values = any, Record = any> extends FormProps, ModalFuncProps {
```

2023-04-20 04:21 UTC, mumiao commented on src/modal/modalWithForm.tsx
> +const ModalForm = (props: ModalProps) => {
```suggestion
const ModalForm = (props: IModalFormProps) => {
```

2023-04-20 04:21 UTC, mumiao commented on src/modal/modalWithForm.tsx
> +import React, { ReactElement, useMemo } from 'react';
![image](https://user-images.githubusercontent.com/22880945/233256902-ee24ba72-ba6f-483c-b2b1-7bef61cffe20.png)
文件名可以直接更新成 `form.tsx`

2023-04-20 04:21 UTC, mumiao commented on src/modal/modalWithForm.tsx
> +const ModalWithForm = (FormComponent: React.ComponentType) => {
```suggestion
const InternalForm = (FormComponent: React.ComponentType) => {
```

2023-04-20 04:21 UTC, mumiao commented on src/modal/modalWithForm.tsx
> +const ModalWithForm = (FormComponent: React.ComponentType) => {
其他地方检查下，名称替换保持完整

2023-04-20 04:21 UTC, mumiao commented on src/modal/modalWithForm.tsx
> +export default ModalWithForm;
```suggestion
export default InternalForm;
```

2023-04-20 04:21 UTC, mumiao commented on src/modal/index.tsx
> +import ModalWithForm from './modalWithForm';
```suggestion
import InternalForm from './form';
```

2023-04-20 04:21 UTC, mumiao commented on src/modal/index.tsx
> +    Form: typeof ModalWithForm;
```suggestion
    Form: typeof InternalForm;
```

2023-04-20 04:21 UTC, mumiao commented on src/modal/index.tsx
> +(WrapperModal as ModalInterface).Form = ModalWithForm;
```suggestion
(WrapperModal as ModalInterface).Form = InternalForm;
```

2023-04-21 03:10 UTC, closed without merging