Refactor/spread sheet
DTStack/dt-react-component pull request #325
Opened 2023-04-23 12:05 UTC by kongshan-zhuyu

# Intro
- Refactor Spreadsheet

# Online
https://kongshan-zhuyu.github.io/dt-react-component/components/spread-sheet

# changeLog
https://dtstack.yuque.com/rd-center/tqk74v/mpvba83z25nrzws2

# Changes
- Refactor Spreadsheet with hooks
- Supplementary unit test
- Optimized demos

2023-04-25 06:20 UTC, mortalYoung requested changes

2023-04-25 06:20 UTC, mortalYoung commented on src/spreadSheet/index.tsx
> +    const _timer = useRef<NodeJS.Timeout>();
这里不应该是 Nodejs.Timeout 吧？应该是 number 吧？如果有类型不匹配的报错，下面的 settimeout 改成 window.settimeout 就行

2023-04-25 06:38 UTC, liuxy0551 commented
+1

2023-04-28 02:25 UTC, mortalYoung approved these changes
+1

2023-05-05 01:44 UTC, merged