Feat v4 slide pane
DTStack/dt-react-component pull request #330
Opened 2023-04-26 11:37 UTC by shiqiWang0

# 右侧面板

## 变动点
- 使用 rc-drawer 重写组件；
- 改写为 函数组件；
- props 变动： 不可任意传入props ，保留原有支持的props， 并新增 bodyStyle 可以复写面板内部的样式，一般多为padding之类的设定；
- 样式与大喜对其 #290 
- container 默认给了 position： fixed 的样式，可以外部覆盖
- 单测增加 
- docs 补充
## 预览地址
## doc

2023-04-27 01:49 UTC, mortalYoung requested changes

2023-04-27 01:49 UTC, mortalYoung commented on src/slidePane/index.tsx
> +}: PropsWithChildren<{}> & ISlidePaneProps) => {
不能直接写成 `PropsWithChildren<ISlidePaneProps>` 酱紫吗 0.0

2023-04-27 01:49 UTC, mortalYoung commented on src/slidePane/index.tsx
> +    let rootStyle: any = {
```suggestion
    let rootStyle: React.CSSProperties = {
```

2023-04-28 02:25 UTC, mortalYoung approved these changes
+1

2023-04-28 07:34 UTC, mortalYoung requested changes

2023-04-28 07:34 UTC, mortalYoung commented on src/slidePane/demos/basic.tsx
> +                    width: `${width}%`,
有没有什么办法可以让这些 style 不需要写，或者只需要写 width 就好

2023-04-28 07:46 UTC, shiqiWang0 commented on src/slidePane/demos/basic.tsx
> +                    width: `${width}%`,
因为各个子产品中自定义的样式比较多， 例如height ，top 等 ，如果删掉会不会可能影响比较大

2023-04-28 07:47 UTC, mortalYoung commented on src/slidePane/demos/basic.tsx
> +                    width: `${width}%`,
讲道理的话 我推荐干掉，但是干掉改动太大，感觉子产品改起来很难改。那就先保留吧

2023-04-28 07:48 UTC, mortalYoung approved these changes

2023-04-28 10:03 UTC, merged