feat: add table component
DTStack/dt-react-component pull request #356
Opened 2023-06-19 02:24 UTC by JackWang032

## Table组件
#354  
新增`Table`组件
- 完全兼容`antd` `Table`
- columns新增tooltip属性

[预览地址](https://jackwang032.github.io/dt-react-component/components/table)

2023-06-19 03:03 UTC, mumiao commented on src/table/index.tsx
> +            ref={ref}
这里是在修正table组件的ref对象么

2023-06-20 02:11 UTC, mortalYoung requested changes

2023-06-20 02:11 UTC, mortalYoung commented on src/table/index.tsx
> +const forwardTable = forwardRef(Table) as RefTable;
Table 上本身会挂上一些 Columns, Summary 之类的东西，貌似是丢了吧？

2023-06-20 02:11 UTC, mortalYoung commented on src/table/index.tsx
> +            className={`.dtc-table ${className || ''}`}
多个 className 用 classnames 来做吧，可读性会更好一些

2023-06-20 02:11 UTC, mortalYoung commented on src/table/index.tsx
> +    const cols = convertColumns(columns);
需要考虑 useMemo 不

2023-06-20 05:56 UTC, mumiao commented
类型检查挂了

2023-06-20 07:17 UTC, mumiao approved these changes

2023-06-20 07:17 UTC, merged