Feat image
DTStack/dt-react-component pull request #395
Opened 2023-10-10 06:36 UTC by LuckyFBB

#390 

1. 新增 useIntersectionObserver hook，为图片懒加载做铺垫

2. 新增 Image 组件，内置懒加载选项，统一产品中 src 引入方式

2023-10-10 08:31 UTC, mumiao commented on src/useIntersectionObserver/index.ts
> +        const observer = new IntersectionObserver(callback, options);
Image组件还木有，可以打个WIP

2023-10-12 02:02 UTC, LuckyFBB commented on src/useIntersectionObserver/index.ts
> +    options: IntersectionObserverInit = {}
IntersectionObserver 源代码有默认设置这些默认值，所以不需要传入

2023-10-16 06:26 UTC, mortalYoung requested changes

2023-10-16 06:26 UTC, mortalYoung commented on src/image/index.tsx
> +                setLoading(false);
不放 finally 里么

2023-10-20 03:42 UTC, mumiao commented on src/image/index.tsx
> +function imgPromise(src: string) {
```suggestion
function loadImage(src: string) {
```

2023-10-24 06:46 UTC, mumiao commented
+1

2023-10-24 06:46 UTC, merged