feat(filterrules): add FilterRules
DTStack/dt-react-component pull request #407
Opened 2023-11-05 13:59 UTC by LuckyFBB

#406 

[实现思路](https://luckyfbb.github.io/blog/react/filter-rules)

2023-11-06 03:47 UTC, mortalYoung requested changes

2023-11-06 03:47 UTC, mortalYoung commented on src/filterRules/index.md
> +| isEdit        | 编辑/查看状态              | `boolean`                                       | `true`  |
isEdit 这个名字太业务化了，不如直接叫 disabled

2023-11-06 03:47 UTC, mortalYoung commented on src/filterRules/index.md
> +| initRowValues | 新增的数据默认值           | `T`                                             | `false` |
既然 value 是数据，这个不如叫 initValue 或者 defaultValue 都行

2023-11-06 03:47 UTC, mortalYoung commented on src/filterRules/index.md
> +| type       | 条件节点类型               | `number`            | -      |
这个的类型不用枚举值么

2023-11-10 08:04 UTC, mortalYoung requested changes

2023-11-10 08:04 UTC, mortalYoung commented on src/filterRules/demos/basicUnController.tsx
> +import { INIT_DATA, INIT_ROW_VALUES, IRow } from './basic';
可以把数据单独放一个文件里，现在这个方式引会导致 demo 展示的时候 basic.tsx 的内容也展示

2023-11-14 02:54 UTC, mortalYoung approved these changes
+1

2023-11-14 07:41 UTC, mumiao commented
+1

2023-11-14 07:41 UTC, merged