fix(slidepane): scroll slidepane content without header
DTStack/dt-react-component pull request #423
Opened 2023-12-01 08:32 UTC by LuckyFBB

#421

2023-12-01 10:34 UTC, mortalYoung requested changes
blockHeader 为啥有改动呢

2023-12-04 01:49 UTC, LuckyFBB commented
> blockHeader 为啥有改动呢

我确认一下，理论上时咩有的

2023-12-06 05:54 UTC, mumiao approved these changes

2023-12-06 05:55 UTC, mumiao commented
+1

2023-12-06 05:55 UTC, merged