feat(useModal): develop useModal
DTStack/dt-react-component pull request #427
Opened 2023-12-22 06:35 UTC by jin-sir

# Intro
- add useModal hook

2023-12-29 09:09 UTC, mortalYoung commented
来个 Previewer 呗

2023-12-29 09:21 UTC, jin-sir commented
https://dtstack.github.io/dt-react-component/components/use-modal

2023-12-29 09:29 UTC, mortalYoung requested changes

2023-12-29 09:29 UTC, mortalYoung commented on src/useModal/demos/basic.tsx
这个 demo 显得有点无的放矢了。感觉只是仅仅说了一下这个 hook 的用法。搞个真实业务场景下会用的情况

2024-01-02 11:19 UTC, LuckyFBB commented
> https://dtstack.github.io/dt-react-component/components/use-modal

应该不是这个地址吧，应该是你自己仓库的那个来着

2024-02-02 08:44 UTC, mortalYoung approved these changes
+1

2024-02-23 02:40 UTC, LuckyFBB commented
+1

2024-09-03 07:43 UTC, merged