feat(slidepane): add footer and extends DrawerProps
DTStack/dt-react-component pull request #440
Opened 2024-01-31 07:09 UTC by LuckyFBB

1. 支持传入 footer 属性，Drawer 底部的按钮操作
2. header 和 footer 固定，中间内容 content 超出高度滚动(包含 padding)
3. 继承 DrawerProps 修改 ts 类型。将 visible 改为 deprecated，支持 open
4. 删除默认的距离顶部 64px，支持通过 rootstyle 修改，例子 **抽屉距顶部高度** (目前产品都是用 64px)

2024-02-01 02:33 UTC, mortalYoung requested changes
另外看看是不是有必要实现 Drawer + Alert，我之前在我们产品里看到过类似的需求

2024-02-01 02:33 UTC, mortalYoung commented on src/slidePane/index.tsx
> +    }, [open, visible]);
这里的 deps 可以直接给 composeOpen 么

2024-02-01 06:25 UTC, LuckyFBB commented
> 另外看看是不是有必要实现 Drawer + Alert，我之前在我们产品里看到过类似的需求

问了一下 UI 小姐姐，目前是有这种场景的，晚点我改动一下~

2024-02-02 08:28 UTC, mortalYoung requested changes

2024-02-02 08:28 UTC, mortalYoung commented on src/slidePane/index.tsx
> +                    <div className={classNames(`${slidePrefixCls}-footer`, bodyClassName)}>
footer 上也需要 bodyClassName 么

2024-02-07 10:02 UTC, mumiao commented
+1

2024-02-07 10:02 UTC, merged