update empty and add Empty.Placeholder
DTStack/dt-react-component pull request #441
Opened 2024-01-31 12:28 UTC by LuckyFBB

### 更新 Empty 组件
1. 添加 size 属性，`default | large` 两个值，分别对应 height: 80 和 height: 100
2. 删除 height 属性，使用 size 来设置两种类型，其余情况可以用使用 antd4.x Empty 的 `imageStyle` 来替代
3. props 继承 antd4.x EmptyProps

### 新增 Empty.Placeholder 组件
**背景**
在我们产品中，经常出现如下代码，经常使用三元运算符来判断展示什么内容
```jsx
{ruleGroupList.length ? (
   <div className="dt-header-content">Content</div>
) : (
  <Empty description={<span>暂无规则集</span>} />
)}
```

添加 Empty.Placeholder 来简化该操作
```jsx
<Empty.Placeholder show={ruleGroupList.length} description={<span>暂无规则集</span>}>
  <div className="dt-header-content">Content</div>
</Empty.Placeholder>
```

2024-02-22 15:41 UTC, HaydenOrz requested changes

2024-02-22 15:41 UTC, HaydenOrz commented on src/empty/index.tsx
> +            {show ? (
当显示非空内容时多渲染了一个 div.etc-empty  这是不必要的，另外这可能导致children 的height： 100% 失效

2024-02-22 15:41 UTC, HaydenOrz commented on src/empty/index.tsx
> +        show,
是否考虑改为isEmpty 这好像更容易懂一些

2024-02-23 01:34 UTC, HaydenOrz commented on src/empty/index.tsx
> +        render,
是否考虑命名为 extra ，antd 英文文档对于它的描述如下图所示
![image](https://github.com/DTStack/dt-react-component/assets/58289241/6723a884-b4bc-4d30-8467-5299514100d9)

2024-02-23 07:13 UTC, HaydenOrz approved these changes

2024-08-23 07:23 UTC, liuxy0551 approved these changes

2024-09-02 06:25 UTC, liuxy0551 commented
我看最后一个 commit 是把 `isEmpty` 改名为 `empty`，但是好像直接看整个 PR 的 diff，发现还是有 `isEmpty`

2024-09-03 07:47 UTC, LuckyFBB commented
> 我看最后一个 commit 是把 `isEmpty` 改名为 `empty`，但是好像直接看整个 PR 的 diff，发现还是有 `isEmpty`

改了，在 check 一下吧

2024-09-11 02:59 UTC, liuxy0551 approved these changes

2024-09-11 03:00 UTC, merged