feat(blockheader): support activeExpand and change callname to onExpand
DTStack/dt-react-component pull request #447
Opened 2024-02-28 10:26 UTC by LuckyFBB

#438 

添加 activeExpand 

更改 onChange 为 onExpand

2024-02-29 11:43 UTC, mortalYoung requested changes

2024-02-29 11:43 UTC, mortalYoung commented on src/blockHeader/index.tsx
> +    activeExpand?: boolean;
为啥不直接叫 expand 呢 0.0

2024-03-07 06:28 UTC, mortalYoung approved these changes
+1

2024-03-07 07:22 UTC, liuxy0551 commented on src/blockHeader/index.tsx
> +    const currentExpand = isControlled(props) ? expand : internalExpand;
当父级传入的 expand 为 false 且 defaultExpand 为 true 时，currentExpand 的值会是 true，是否需要考虑父级传入的 expand 和 defaultExpand 共存时两者的优先级到底谁高

2024-03-07 07:22 UTC, liuxy0551 commented on src/blockHeader/index.tsx
> +    expand?: boolean;
这个组件的交互比较简单，是否传入一个 expand 就好了，可以考虑去除 defaultExpand 参数，不过需要考虑已经使用的子产品

2024-03-07 07:24 UTC, LuckyFBB commented on src/blockHeader/index.tsx
> +    const currentExpand = isControlled(props) ? expand : internalExpand;
受控和非受控的方式了。。

如果是 expand 是需要通过 onExpand 事件来改变的，对应的是 受控模式
defaultExpand 不需要通过 onExpand 事件来改变的，对应的是 非受控模式

2024-03-07 07:26 UTC, LuckyFBB commented on src/blockHeader/index.tsx
> +    expand?: boolean;
如果只考虑一种模式的应该是可以的， 如果是两种的情况下，应该是不能去除掉的

2024-09-03 08:07 UTC, liuxy0551 approved these changes

2024-09-09 03:03 UTC, liuxy0551 approved these changes

2024-09-09 03:03 UTC, merged