feat(statustag): support bg statusTag
DTStack/dt-react-component pull request #450
Opened 2024-03-06 08:15 UTC by LuckyFBB

#448 

### 添加功能
添加带有背景色的状态标签
支持自定义 icon

### 修改
移除 showBorder 属性，使用 type 替换，支持 `deafult | outline | fill` 三种类型，分别对应 无边框 | 有边框 | 背景色

原有的 type 属性迁移到 color 属性上，内置 6 种类型，`warning | error | success | run | stopped | frozen` 符合 UI5.0 的色阶规范；支持自定义 color 颜色(**支持 RGB 和 十六进制**)，在 fill 类型下，背景色是 color + 0.3 的透明度组合而成

2024-03-07 08:06 UTC, liuxy0551 commented on src/statusTag/index.md
> +| type    | 设置状态类型                                                | `default \| outline \| fill`                                          | `default` |
感觉 type 的命名不够表义，是否考虑类似 bgType 等命名，体现背景色相关

2024-03-07 08:13 UTC, LuckyFBB commented on src/statusTag/index.md
> +| type    | 设置状态类型                                                | `default \| outline \| fill`                                          | `default` |
> 感觉 type 的命名不够表义，是否考虑类似 bgType 等命名，体现背景色相关

default 无边框，outline 有边框，fill 填充，思路来源 ant icon 类型(纯纯没有想到更合适的

2024-03-07 08:15 UTC, LuckyFBB commented on src/statusTag/style.scss
> +$frozen_color: #B1B4C5;
> 不复用的颜色变量是否直接在使用的地方写色号，或者背景色也用颜色变量，两处统一就好

目前看起来是可以删掉变量了，之前没有遍历的时候多处使用了

2024-03-11 03:16 UTC, mortalYoung requested changes

2024-03-11 03:16 UTC, mortalYoung commented on src/statusTag/index.tsx
> +export type PresetColorType = (typeof PresetColorTypes)[number] | string;
这么写是不是没有类型提示了，建议写成
```suggestion
export type PresetColorType = (typeof PresetColorTypes)[number] | (string & {});
```

2024-03-11 06:34 UTC, LuckyFBB commented
font-size 12px
border-color #d8dae2

2024-09-03 08:10 UTC, liuxy0551 approved these changes

2024-09-04 07:04 UTC, merged