feat(blockheader): supprt large size and change some props name
DTStack/dt-react-component pull request #478
Opened 2024-09-02 03:27 UTC by LuckyFBB

#### 变更类型

请选择以下选项以描述 PR 的类型：

- [ ] Bug 修复（修复现有问题）
- [x] 新功能（添加了一个功能）
- [ ] 代码优化（性能改进、代码重构）
- [ ] 文档更新
- [ ] 单测新增或修改
- [ ] 其他（请说明）：

#### 相关问题
#476 

#### 变更内容
新增 16px 的标题

更改 beforeTitle 为 addonBefore；更改 afterTitle 为 description；showBackground 改为 background

#### 详细描述

#### 对应 Previewer

2024-09-04 09:23 UTC, mortalYoung requested changes

2024-09-04 09:23 UTC, mortalYoung commented on src/blockHeader/index.tsx
>      titleClassName?: string;
这个组件貌似不支持传 style，然后这个几个 className 也有点混淆不清

2024-09-04 09:23 UTC, mortalYoung commented on src/blockHeader/index.tsx
>      if (hasBottom) bottomStyle = { marginBottom: 16 };
个人感觉是 margin 的属性貌似更应该交给用户自己做

2024-09-04 09:23 UTC, mortalYoung commented on src/blockHeader/index.tsx
> +                <div className={`${prefixCls}-content ${expand ? 'active' : ''}`}>{children}</div>
这个组件的 className 貌似不符合 BEM 的规范

2024-09-06 07:09 UTC, LuckyFBB commented on src/blockHeader/index.tsx
>      if (hasBottom) bottomStyle = { marginBottom: 16 };
等等再和大家讨论一下吧，和 slidePane 的 top 一样，如果要内置都给内置掉，不内置的话，再干掉

2024-09-09 03:11 UTC, mortalYoung requested changes

2024-09-09 03:11 UTC, mortalYoung commented on src/blockHeader/index.tsx
>      const prefixCls = 'dtc-block-header';
这个变量拿函数外边去吧？貌似没有定义在函数内部的必要

2024-09-09 03:11 UTC, mortalYoung commented on src/blockHeader/index.tsx
> +                <div className={`${prefixCls}__content ${expand ? 'active' : ''}`}>{children}</div>
这个 active 需要改成 BEM 的写法吧？这里用 classNames 来实现吧。上面也几个，比如 text icon 之类的

2024-09-09 07:57 UTC, mortalYoung approved these changes
+1

2024-09-09 07:57 UTC, merged

2024-09-09 10:04 UTC, liuxy0551 commented on src/copy/demos/basic.tsx
>                  <Copy text={text} tooltip={() => `使用 ()=>React.ReactNode，复制该文本`} />
箭头函数的 => 左右帮忙加一下空格吧

2024-09-09 11:13 UTC, LuckyFBB commented on src/blockHeader/demos/basic.tsx
> +    const [description, setDescription] = useState(true);
这里只是想要表达展示与否，具体的传值还是下面赋值的

2024-09-09 11:13 UTC, LuckyFBB commented on src/blockHeader/demos/basic.tsx
> +                description={description && '提示说明文字'}
这个感觉问题不大。
tooltip 的 title 本来就接受一个 false 做为参数。description 可以改成三目

2024-09-09 11:14 UTC, LuckyFBB commented on src/blockHeader/demos/basic.tsx
> +                        onChange={setShowBackground}
这个是变量名字，可改可不改