feat(copy): remove title/hideTooltip, add tooltip
DTStack/dt-react-component pull request #479
Opened 2024-09-03 09:50 UTC by LuckyFBB

#### 变更类型

请选择以下选项以描述 PR 的类型：

- [ ] Bug 修复（修复现有问题）
- [ ] 新功能（添加了一个功能）
- [x] 代码优化（性能改进、代码重构）
- [ ] 文档更新
- [ ] 单测新增或修改
- [ ] 其他（请说明）：

#### 相关问题
#477 

#### 变更内容
删除现有的 title/hideTooltip 属性

更改为 tooltip 属性，`React.ReactNode | TooltipProps`

传入了 tooltip 属性就展示 <Tooltip/> 组件

tooltip 为 `React.ReactNode` 时转换为 `{ title: tooltip }`

大体设计保持和 Form.Item 的 tooltip 一致

后续目标让 RC 的所有 tooltip 保持一致
#### 详细描述

#### 对应 Previewer

2024-09-03 10:06 UTC, shiqiWang0 commented
这样改之后是不是需要传 tooltip 才给改造后的 copy 组件展示；没改之前的话， 默认就可以展示 复制的 tooltip，这样子产品是不是 用这个组件 就需要传 tooltip 了

2024-09-03 10:37 UTC, LuckyFBB commented
> 这样改之后是不是需要传 tooltip 才给改造后的 copy 组件展示；没改之前的话， 默认就可以展示 复制的 tooltip，这样子产品是不是 用这个组件 就需要传 tooltip 了

是会有这个问题，可以改成 tooltip = “复制”，如果不需要展示 Tooltip 的话就得设置 tooltip = “”

2024-09-04 07:08 UTC, mortalYoung requested changes

2024-09-04 07:08 UTC, mortalYoung commented on src/copy/index.tsx
> +export type LabelTooltipType = TooltipProps | React.ReactNode;
看了一下，貌似 Tooltip 的 title 是支持 renderFunction 的写法的，要不这里后面改成 `TooltipProps['title']` 的写法不知道行不行？

2024-09-04 07:08 UTC, mortalYoung commented on src/copy/index.tsx
> +    return tooltipProps ? (
感觉这里的判断可以优化一下，直接 `return Tooltip` 的 JSX，然后把 `toTooltipProps` 处理后的结果不需要返回 null，只需要返回 title：null 即可

2024-09-09 03:22 UTC, liuxy0551 commented on src/copy/index.md
> -| hideTooltip | 是否隐藏 Tooltip      | `boolean`                | `false`                             |
title 和 hideTooltip 我在 global/release_7.0.x 中看到用的地方还有一些，到时候写到变更记录就好了

2024-09-09 03:22 UTC, liuxy0551 approved these changes

2024-09-09 06:51 UTC, mortalYoung approved these changes
+1

2024-09-09 06:52 UTC, merged