feat(tinytag): replace svg to render
DTStack/dt-react-component pull request #517
Opened 2024-11-11 02:33 UTC by shiqiWang0

#### 变更类型

请选择以下选项以描述 PR 的类型：

- [ ] Bug 修复（修复现有问题）
- [ ] 新功能（添加了一个功能）
- [x] 代码优化（性能改进、代码重构）
- [ ] 文档更新
- [ ] 单测新增或修改
- [ ] 其他（请说明）：

#### 相关问题
关联 issue： #466

#### 变更内容
通过 svg 进行处理， 替换原本通过 css 进行缩放实现 10px 的效果

#### 详细描述
技术方案 

#### 对应 Previewer

2024-11-11 03:47 UTC, LuckyFBB commented on src/tinyTag/index.tsx
> +    color = DEFAULT_COLOR,
我觉得这里要不别传 color 了，直接使用 svg 的 currentColor 做吧？
用 currentColor 需要通过 style/className 来设置颜色，考虑到如果 TinyTag 要做 hover 的时候改变一下颜色，className 应该更好实现。直接传入 color，在这种场景下并不好实现

2024-11-11 05:56 UTC, LuckyFBB commented on src/tinyTag/index.tsx
> +import React, { useEffect, useRef, useState } from 'react';
value 能否改为 ReactNode ，是否对实现有影响？
能否去除 value 属性，直接改为 children 的传入，和 antd 的 Tag 保持一致。。

2024-11-11 07:32 UTC, mortalYoung requested changes

2024-11-11 07:32 UTC, mortalYoung commented on src/tinyTag/index.tsx
> +                    fontFamily="PingFang SC"
这个 fontFamily 可以和咱们的 body 上保持一致么，直接给 PingFang Windows 上会缺失

2024-11-11 11:10 UTC, shiqiWang0 commented on src/tinyTag/index.tsx
> +import React, { useEffect, useRef, useState } from 'react';
这个目前尝试下来不太行， 因为 svg 中绘制 value 是使用 text 和 tspan 完成与设计稿相同的布局， 如果通过传入node，无法通过 svg 绘制

2024-11-11 11:10 UTC, shiqiWang0 commented on src/tinyTag/index.tsx
> +    color = DEFAULT_COLOR,
可以的

2024-11-13 08:18 UTC, jin-sir commented
有个问题，rect 的 stroke-width 默认值是 1 个单位，是向外扩展的，这个 rect 上的 x 设置成0.5会存在一定的问题，还有上面的 paddingWidth 设置为 9，下面的 text 元素设置的 x 又是 4 ，是不是有问题？

2024-11-13 09:26 UTC, shiqiWang0 commented
> 上面的 paddingWidth 设置为 9，下面的 text 元素设置的 x 又是 4 ，是不是有问题？

text 在画布偏移 4的位置绘制， 那计算出来的 width 应该在该基础上 加 4 * 2

2024-11-13 11:09 UTC, mortalYoung requested changes

2024-11-13 11:09 UTC, mortalYoung commented on src/tinyTag/index.tsx
> +    const domRef = useRef<HTMLDivElement>(null);
可以搞一个 useTextSize 的 hook，把这块的逻辑都纳到 hook 里去

2024-11-14 01:58 UTC, jin-sir commented on src/tinyTag/index.tsx
> +                    width={width - 1}
这里加个判断吧？width初始值为0，在第一次渲染时，rect的width变成了 -1，会出现错误
Error: attribute width: A negative value is not valid. ("-1")

2024-11-14 02:20 UTC, shiqiWang0 commented on src/tinyTag/index.tsx
> +                    width={width - 1}
这个 会提取到 hook 里面， 处理掉

2024-11-22 03:00 UTC, jin-sir approved these changes

2024-11-22 03:16 UTC, merged